coordinatorClientError=A coordinator client exception occurred. Cause: {0}
syssvcInternalError=A syssvc internal exception occurred. Cause: {0}
invalidLockOwnerError=An invalid lock owner exception occurred. Cause: {0}
localRepoError=A local repository exception occurred. Cause: {0}
remoteRepoError={0}
sysClientError=A syssvc client exception occurred. Cause: {0}
failConnectControllerError=A data node fail connecting to controller exception occurred. Cause: {0}
serviceNameNotFoundException=An error occured while retrieving the service name for pid {0}